sudo: false
language: node_js
node_js: 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache: yarn
script: yarn verify

deploy:
  - provider: npm
    skip-cleanup: true
    email: conartist6@gmail.com
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    committer-from-gh: true
    keep-history: false
    local-dir: pages/out/docs
    on:
      branch: master
      tags: true
